version: "3.9"

services:

  mysql:
    image: mysql:8.0.32
    env_file: ./env/mysql.env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: ./
    env_file: ./env/app.env
    ports:
      - "8080:8080"
      - "5005:5005"
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data: